name: black_death
description: a flutter game based on climate change.
version: 0.0.1

environment:
  sdk: '>3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.65.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  audioplayers: ^5.2.1 
  marquee: ^2.2.0
  cloud_firestore: ^4.13.6

flutter:
  assets:
    - assets/audio/
    - assets/images/
  uses-material-design: true
